#!/data/data/com.termux/files/usr/bin/bash
#################################################
#
# Pure-aarch64-XFCE4-Termux-VNC-Desktop
# By RajDhinge
#
# Last modified: Fri Nov 13 1:31:26 AM IST 2021
#################################################
clear
#Variables
Green='\033[0;32m' 
Yellow='\033[1;33m'
White='\033[1;33m'
Red='\033[0;31m' 
#Get ip address
printf "${Yellow}[*] ${Green}Starting Servers\n"
ifconfig 2>/dev/null | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p' > ip
password='1234567'

vncserver -list|grep :|awk '{print $1}'|grep : > livevnc  && sleep 5

#Terminate and clean vnc server
for PORT in `cat livevnc`
do
    if [ -f "/data/data/com.termux/files/usr/tmp/.X`echo $PORT|awk -F ':' '{print $2}'`-lock" ]; then
        rm -rf /data/data/com.termux/files/usr/tmp/.X*-lock
        rm -rf /data/data/com.termux/files/usr/tmp/.X11-unix/X*
    fi
    vncserver -kill $PORT >/dev/null 2>&1
    if [ -f "/data/data/com.termux/files/usr/tmp/.X`echo $PORT|awk -F ':' '{print $2}'`-lock" ]; then
        rm -rf /data/data/com.termux/files/usr/tmp/.X*-lock
        rm -rf /data/data/com.termux/files/usr/tmp/.X11-unix/X*
    fi
done

#Terminate all xfce sessions
pkill xfce4-session >/dev/null 2>&1 &
rm -rf /data/data/com.termux/files/home/.vnc/passwd

#Start VNC and xfce4-session
vncserver >/dev/null 2>&1 << EOD
${password}
${password}
"n"
EOD

export DISPLAY=:1
xfce4-session >/dev/null 2>&1 &
clear

#kill active servers
pkill nginx
pkill php-fpm

#Boot server
mysqld_safe >/dev/null 2>&1 &
sleep 1
nginx  >/dev/null 2>&1
php-fpm >/dev/null 2>&1
sleep 1

printf "${Yellow}[*] ${Green}Servers are up\n\n"
termux-wake-lock

printf "${Yellow}[*] ${Green}wordpress links : \n${White}"
printf "Local ip : http://`cat ip`:8080/wordpress"
printf "\nLocal ip : http://`cat ip`:8080/adminer.php"

`curl -s ifconfig.co >dev\null 2>&1`
if [ $? -eq 0 ]; then
    printf "\npublic ip : http://`curl -s ifconfig.co`:8080/wordpress"
    printf "\npublic ip : http://`curl -s ifconfig.co`:8080/adminer.php"
fi

printf "\n${Yellow}[*] ${Green}VNC is up\n Local IP: ${Yellow}`cat ip` \n ${Green}Port: ${Yellow}509`vncserver -list|grep :|awk '{print $1}'|grep :|awk -F ':' '{print$2}'`${Green}\n Password : ${Yellow}$password\n${Green}${White}"
printf "${Yellow}[*] ${Green}SSH is up\n Local IP: ${Yellow}`cat ip` \n ${Green}Port: ${Yellow}8022${Green}\n Password : ${Yellow}$password ${White}\n"
sshd

#Clean files
rm -rf ip
rm -rf livevnc
