#!/data/data/com.termux/files/usr/bin/bash
#################################################
#
# Pure-aarch64-XFCE4-Termux-VNC-Desktop
# By RajDhinge
#
# Last modified: Fri Nov 13 1:31:26 AM IST 2021
#################################################

#Variables
Green='\033[0;32m' 
Yellow='\033[1;33m'
White='\033[1;33m'
Red='\033[0;31m' 
#Get ip address
ifconfig 2>/dev/null | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p' > ip
password='1234567'

figlet "Setting VNC"
printf "${Yellow}[*] ${Green}Setting up Xfce session\n"
printf "${Green} Please wait... \n Your ip is ${Yellow}`cat ip`${Green} \n this may take a while...\n" && sleep 1
printf "${Yellow}[*] ${Green}Terminating active vnc server's if any \n"
printf "${Yellow}[*] ${Green}Calling hitman \n"
printf "${Yellow}[*] ${Green}Hitman arrived\n"
vncserver -list|grep :|awk '{print $1}'|grep : > livevnc  && sleep 5

#Terminate and clean vnc server
for PORT in `cat livevnc`
do
    if [ -f "/data/data/com.termux/files/usr/tmp/.X`echo $PORT|awk -F ':' '{print $2}'`-lock" ]; then
        rm -rf /data/data/com.termux/files/usr/tmp/.X*-lock
        rm -rf /data/data/com.termux/files/usr/tmp/.X11-unix/X*
    fi
    vncserver -kill $PORT 
done
#Terminate all xfce sessions
pkill xfce4-session >/dev/null 2>&1 &
rm -rf /data/data/com.termux/files/home/.vnc/passwd
printf "${Yellow}[*] ${Green}Hitman left\n"

printf "${Yellow}[*] ${Green}We are about to start vnc server\n"

#Start VNC and xfce4-session
vncserver << EOD
${password}
${password}
"n"
EOD

export DISPLAY=:1
xfce4-session >/dev/null 2>&1 &
clear

figlet "Setting"
figlet "Wordpress" 
sleep 2
printf "${Yellow}[*] ${Green}Setting up wordpress and nginx\n"

#kill active servers
pkill nginx
pkill php-fpm

#Boot server
mysqld_safe &
sleep 1
nginx
php-fpm
sleep 1

printf "${Yellow}[*] ${Green}Wordpress is up\n"

sleep 3 && clear 
figlet "Servers" 
figlet "Active"
termux-wake-lock
printf "${Yellow}[*] ${Green}Wavelock aquired\n"
printf "${Yellow}[*] ${Green}php-fpm is up\n"
printf "${Yellow}[*] ${Green}mysql is up\n"
printf "${Yellow}[*] ${Green}nginx is up\n"
printf "${Yellow}[*] ${Green}wordpress is up\n${White}"
printf "\nLocal ip : http://`cat ip`:8080/wordpress"
printf "\nLocal ip : http://`cat ip`:8080/adminer.php"
`curl -s ifconfig.co >dev\null 2>&1`

if [ $? -eq 0 ]; then
    printf "\npublic ip : http://`curl -s ifconfig.co`:8080/wordpress"
    printf "\npublic ip : http://`curl -s ifconfig.co`:8080/adminer.php"
fi

printf "\n${Yellow}[*] ${Green}VNC is up\n Local IP: ${Yellow}`cat ip` \n ${Green}Port: ${Yellow}509`vncserver -list|grep :|awk '{print $1}'|grep :|awk -F ':' '{print$2}'`${Green}\n Password : ${Yellow}$password\n${Green}\n keep this termux session active\n \n${White}"
printf "${Yellow}[*] ${Green}SSH is up\n Local IP: ${Yellow}`cat ip` \n ${Green}Port: ${Yellow}8022${Green}\n Password : ${Yellow}$password\n \n${White}"
sshd

#Clean files
rm -rf ip
rm -rf livevnc
